version: '2'
services:
  web:
    image: nginx:1.13.8-alpine
    links:
      - php
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ulimits:
      nproc: 50000
    environment:
      TZ: Europe/Moscow
    volumes_from:
      - php
  php:
    build: php-7.0-fpm-custom
    environment:
      - TYPO3_CONTEXT=Development/Docker
    links:
      - db
    volumes:
      - ./vk_proj:/var/www/html
  db:
    image: mysql:5.6
    environment:
      - MYSQL_ROOT_PASSWORD=password
    volumes:
      - ./mysql:/var/lib/mysql
    ports:
      - "3306:3306"
