version: '2.1'
services:
  web:
    image: nginx:1.13.8-alpine
    links:
      - php
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ulimits:
      nproc: 50000
    environment:
      TZ: Europe/Moscow
    volumes_from:
      - php
  php:
    build: php-7.1
    environment:
      - TYPO3_CONTEXT=Development/Docker
      - COMPOSER=/var/www/html/vendor/composer.json
      - COMPOSER_VENDOR_DIR=/var/www/html/vendor
    links:
      - db
    volumes:
      - ./vk_proj:/var/www/html
  db:
    image: mysql:5.6
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=polls_application
    volumes:
      - ./mysql:/var/lib/mysql
      # - ./initdb.d here we'll add sql template table creation
    ports:
      - "3306:3306"
