version: '2.1'
services:
  web:
    image: nginx:1.13.8-alpine
    links:
      - php
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    # ulimits:
    #   nproc: 50000
    environment:
      TZ: Europe/Moscow
    volumes_from:
      - php
  php:
    build: php-7.2
    environment:
      TZ: Europe/Moscow
    links:
      - db
    volumes:
      - ./vk_proj:/var/www/html
    expose:
      - 9000
  db:
    image: mysql:5.6
    environment:
      - MYSQL_ROOT_PASSWORD=password
    volumes:
      - ./mysql.d/conf.d:/etc/mysql/conf.d
      - ./mysql.d/initdb.d:/docker-entrypoint-initdb.d
      - ./mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
